In [1]:
"""
سوال 1(
یک نوت بوک پایتونی درست کنید و در آن یک list دلخواه شامل اعداد float، int و همچنین str درست کنید.
بر روی آن for بزنید و تمام عناصر عددی و بزگتر از 20 آن را چاپ کنید. 
"""

#1stmethod | type-checking

my_list = [5, 5.5, 4, 3, 50, 550.2, 22, 1, -1, 'test']

for item in my_list:
    if isinstance(item, (int, float)) and item > 20:
        print(item)

print('='*20)

#2nd-method | try-except

my_list = [5, 5.5, 4, 3, 50, 550.2, 22, 1, -1, 'test']

for item in my_list:
    try:
        if item > 20:
            print(item)
    except TypeError:
        print(f"Warning: '{item}' is not a numeric value and was skipped.")

print('='*20)

#3nd | Filter Out Non-Numeric Elements

my_list = [5, 5.5, 4, 3, 50, 550.2, 22, 1, -1, 'test']

numeric_list = list(filter(lambda x: isinstance(x, (int, float)), my_list))

for item in numeric_list:
    if item > 20:
        print(item)

print('*'*20)

50
550.2
22
50
550.2
22
50
550.2
22
********************


In [2]:
"""
سوال 2(
یک دیکشنری درست کنید.
در یک for از کاربر اسم و نمره بگیری د و این دیکشنر ی را مقداردهی کنید، طوری که کلیدها نام و مقادیر معدل باشد.
در آخر معدل این افراد را چاپ کنید
"""

scores = {}

while True:
    name = input("Enter the name (or press Enter to finish): ")
    if name == "":
        break
    
    score = int(input(f"Enter the score for {name}: "))
    scores[name] = score

print("Scores:")
for name, score in scores.items():
    print(f"{name}: {score}")

Scores:
amir: 12
parsa: 20


In [3]:
"""
سوال 3(
یک لیست دلخواه بسازید و تعداد غی ر تکرار ی های آن را بشمارید.
راهنمایی: ابتدا آن را تبدیل به set کنید.
"""
# method 1
import numpy as np

list = np.random.randint(0,5, size=(10))
# delete duplicates
num_non_duplicates = len(set(list))

print(f'My list:\n{list}')
print(f'Number of non-duplicates:\n{num_non_duplicates}')


# method 2
import numpy as np

list = np.random.randint(0,5,size=(10))
print(f'My list:\n{list}')
num_non_duplicates = len(np.unique(list))
print(f'Number of non-duplicates:\n{num_non_duplicates}')

set_list = set(list)



My list:
[3 0 4 1 3 1 4 3 2 0]
Number of non-duplicates:
5
My list:
[2 3 3 2 4 1 3 3 2 3]
Number of non-duplicates:
4


In [4]:
"""
سوال 4(
 یک نوت بوک پایتونی ایجاد کرده و دو آرایه از نوع numpy به نام ها ی a و b با طول یکسان بسازید.
الف ( حال حاصل جمع بردار ی آن ها را در متغیر c ریخته و در نهایت چاپ کنید.
ب( آرایه c را در عدد ثابت 5 ضرب کرده و نتیجه را چاپ کنید.
ج( میانگین اعدد آرایه c را چاپ کنید
"""
import numpy as np

a = np.array(np.random.randint(0, 11, size=5))
b = np.array(np.random.randint(0, 11, size=5))

c = a + b
print(c)
print(c*5)
print((c*5).mean())

[ 8  9  8 11 12]
[40 45 40 55 60]
48.0


In [5]:
"""
سوال 5(
یک تابع به نام five_np در پایتون تعریف کنید که ورودی اش یک عدد باشد و خروجی اش یک ماتریس پر از 5 باشد.
برا ی مثال با فراخوانی five_np(2 )یک ماتریس نامپای 2 در 2 که در همه خانه های آن 5 هست برگرداند.
"""

import numpy as np

def five_np(num):
    return np.full((num, num), 5)

print(five_np(2))

[[5 5]
 [5 5]]


In [6]:
"""
سوال 6(
 یک وکتور)آرایه یک بعدی( پایتون به صورت رندم و تصادفی با طول 500.000 بسازید. 
 و با پیاده ساز ی به دو روش زیر زمان اجرا را مقایسه و چاپ کنید
 الف( یک تابع پایتونی بنویسید که با for زدن روی این آرایه بزرگترین عدد را برگرداند.
ب( با توابع خود numpy که میدانی م پیاده ساز ی vectorize انجام داده اند ماکزیمم این لیست را حساب کنید.
"""
import numpy as np

arr = np.random.rand(500000)
print(arr)

# A
def max_num(arr):
    max_num = arr[0]
    for num in arr:
        if num > max_num:
            max_num = num
    return max_num
print(max_num(arr))

# B
print(np.max(arr))


[0.54372747 0.10344875 0.60598412 ... 0.32781391 0.90240595 0.08226681]
0.9999988821505873
0.9999988821505873


In [16]:
"""
سوال 7(
 یک عکس دلخواه لود کنید، تمام خانه های آن را به عالوه 10 کنید و ذخیره کنید. عکس نهایی و عکس اولیه را در پوشه تمرین بزارید و
ارسال کنید
"""
from PIL import Image
import numpy as np
import os

def load_and_modify_image(image_path, output_folder):
    # Load the image
    img = Image.open(image_path)
    img = img.convert('RGB')  # Ensure image is in RGB format

    # Convert image to numpy array
    data = np.array(img)

    # Add 10 to each pixel. Since pixel values must be in [0,255], we clamp them using np.clip
    modified_data = np.clip(data + 10, 0, 255)
    
    # Convert numpy array back to image
    modified_img = Image.fromarray(modified_data.astype('uint8'), 'RGB')

    # Define file paths
    original_image_path = os.path.join(output_folder, 'original_image.png')
    modified_image_path = os.path.join(output_folder, 'modified_image.png')

    # Save the original image
    img.save(original_image_path)

    # Save the modified image
    modified_img.save(modified_image_path)

    print(f"Images saved in {output_folder}")
    print("Original image path:", original_image_path)
    print("Modified image path:", modified_image_path)

# Specify the image path and output folder
image_path = 'tmpcxba3tn4-min.png'  # Update this path to your image's path
output_folder = 'Q7_image'  # Define or update output directory

# Create output directory if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Call the function
load_and_modify_image(image_path, output_folder)

Images saved in Q7_image
Original image path: Q7_image/original_image.png
Modified image path: Q7_image/modified_image.png


In [2]:
"""
سوال 8(
یک برنامه پایتونی بنویسید که تعداد کاراکترها ی منحصر به فرد استفاده شده در یک فایل txt را برگرداند.
برا ی این کار کافی است کل فایل txt را بخوانی د. در یک متغیر بریزید
بعد تبدیل به set کنید
در نهایت طول set را چاپ کنید
"""
with open('sample.txt', 'r') as file:
    text = file.read()

unique_char = set(text)
print(unique_char)

print('Number of unique characters:', len(unique_char))


{'B', 'n', ',', '–', 'i', 'g', 'v', 'V', 'z', 'E', 'p', 'q', 'x', 't', 'm', '\n', 'u', '.', 'w', 'T', 'H', ' ', 'k', 's', 'l', 'a', 'o', 'I', 'r', 'd', 'h', 'f', 'y', 'c', 'L', 'A', 'b', ':', '-', 'e'}
Number of unique characters: 40


In [9]:
"""
سوال 9(
تصویر یک چهره دلخواه را در پایتون لود کرده و فقط ناحیه چهره آن را با پایتون نمایش دهید )با numpy ناحیه را مشخص کنید، به صورت
code-hard یا همان وارد کردن دستی اعداد در کد.(
"""



'\nسوال 9(\nتصویر یک چهره دلخواه را در پایتون لود کرده و فقط ناحیه چهره آن را با پایتون نمایش دهید )با numpy ناحیه را مشخص کنید، به صورت\ncode-hard یا همان وارد کردن دستی اعداد در کد.(\n'