In [15]:
import numpy as np
import math
import sys
# in command miad version package haro mide va grep kardam ke faghat numpy ro bede
!which python
!python --version
!pip freeze | grep "numpy"
print(sys.executable)

/bin/python
Python 3.12.2
numpy==1.26.4
/bin/python


In [4]:
# creating array
a = np.array([1,2,3])
print(a)
print('='*80)
# ones matrix
a = np.ones(3)
print(a)
print('='*80)
# zeors
a = np.zeros(3)
print(a)
print('='*80)
# generates random floating-point numbers uniformly distributed between 0 and 1 (exclusive of 1)
a = np.random.random()
print(a)
print('='*80)

a = np.random.random(size=5)
print(a)
print('='*80)

# 2d
a = np.random.random(size=(5,5))
print(a)
print(type(a)) # ndarray : n-dimensional array (array haye chand boudi) ke be ina migan tensor
print('='*80)

# to list mamoli mishe inkaro kard mesle addad behesh negah mikone
a = [1,2,3] + [2,3,4,5,6]
print(a)
print('='*80)

# vali to np.array chon tensor hast, hatman bayad vectorize behesh negah koni va len yeksan bashe
a = np.array([1,2,3])
b = np.array([1,1,1])
print(a+b)
print('='*80)
a = np.array([1,2,3])
b = np.ones(3)
print(a+b)
print('='*80)


"""
dar halati ke ba addad ha hastim nmishe [1,2,3]+10 kard...
vali ba np array ha mishe
"""
# broadcasting
a = np.array([1,2,3]) + 2
print(a)
print('='*80)

"""
kolan hamon kar haye ke mikonim element be element(elementvize) mesle matrix(tensor)
anjam mide
msln to ML bias ro ba multiply kardan ye nouron to 0.7 mitonam kole
element hasho * 0.7 konam...
"""

# Aggregation
a = np.array([1,2,3])
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.prod(a)) # multiplying all the elements together
print(np.std(a)) # standard deviation
print(np.mean(a)) # average
print(math.sqrt(1))


[1 2 3]
[1. 1. 1.]
[0. 0. 0.]
0.8867254344825319
[0.78157239 0.55755435 0.77444313 0.19073867 0.05975045]
[[0.71533155 0.28438133 0.14820935 0.55738324 0.27919179]
 [0.26929684 0.36346656 0.41563249 0.60140372 0.05367265]
 [0.00682215 0.86950767 0.75834614 0.06328155 0.07223318]
 [0.81314534 0.82346978 0.72198394 0.78270316 0.46077255]
 [0.39697319 0.39802974 0.37363131 0.65581573 0.33546504]]
<class 'numpy.ndarray'>
[1, 2, 3, 2, 3, 4, 5, 6]
[2 3 4]
[2. 3. 4.]
[3 4 5]
3
1
6
6
0.816496580927726
2.0
1.0


In [12]:
import numpy as np

def statistics(nparray):
    a = np.mean(nparray)
    b = np.std(nparray)
    sumation = np.sum(nparray)
    return a,b,sumation

tensor = np.array([44,5,6,87,5,56,20])

mean, deviation, sumation = statistics(tensor)
print(f'mean is {mean} / deviation is {deviation} / sumation is {sumation}')
print('='*20)
"""
data type haye tensor bayad hamgen bashan vagarna kar nmikone...
msln age to tensor string bezaram, data type kole tensor string mishe
"""
print(tensor.dtype)

print('='*20)
# bezor ham mitonam data type ro malom konam
a = np.array([44,5,6,87,5,56,20], dtype='float32')
print(a.dtype)
print('='*20)



mean is 31.857142857142858 / deviation is 29.33271489762422 / sumation is 223
int64
float32
